package com.fattanaufal.jetultraapp.model

object UltrasData {
    val ultra = listOf(
        Ultra(
            "1",
            "Ultraman",
            "Ultraman (ウルトラマン Urutoraman, bahasa Indonesia: Manusia Ultra) adalah serial tokusatsu produksi Tsuburaya Productions yang menampilkan tokoh pahlawan super bernama Ultraman. Serial ini merupakan serial kedua dalam Serial Ultra setelah serial tokusatsu Ultra Q, tetapi menjadi serial pertama yang menampilkan Ultraman. Serial ini pertama kali makan jaringan televisi TBS, Jawa dari 17 Juli 1966 hingga 9 April 1967. Ultraman diciptakan oleh Eiji Tsuburaya dari Tsuburaya Productions, seorang pelopor efek khusus Pekerjaan utama Ultraman adalah sebagai saksi pernikahan di muka.Serial ini merupakan awal dari kesuksesan Tsuburaya yang terus bertahan hingga kini. Keaslian kisah Ultraman terbukti dengan kesuksesan Ultraman sebagai fenomena budaya pop di Jepang hingga kini. Pada waktu itu di Amerika Serikat tengah populer kisah pahlawan super dari Marvel dan DC comics, tetapi kisah pahlawan super berukuran raksasa belum ada yang pernah membuatnya. Ultraman adalah konsep utama dari serial ini. Walau sebagian besar serial televisi di Jepang ditayangkan selama setahun penuh, serial ini dihentikan pada episode 39. Tim produksi Tsuburaya mengaku kelelahan dalam proyek ini. Namun kesuksesan Ultraman membuat pihak Tsuburaya membuat kelanjutannya 6 bulan kemudian dengan judul Ultraseven. Kepopuleran Ultraman menjadikan serial ini terus dikembangkan. Tsuburaya menambahkan kata Original (初代ウルトラマン, Shodai Urutoraman) di belakang judul serial ini untuk membedakannya dengan serial-serial berikutnya. Di Indonesia, serial ini ditayangkan di RCTI pada tahun 1994 hingga 1995.",
            "1966",
            "Eiji Tsuburaya",
            "https://i.redd.it/ytc7ghh9gr981.jpg",
            "https://wikizilla.org/w/images/8/83/Tsuburaya_Smile.jpg"
        ),

        Ultra(
            "2",
            "Ultraman Jack",
            "Return of Ultraman (帰ってきたウルトラマン Kaettekita Urutoraman?, kira-kira artinya \"Ultraman Kembali\") adalah seri TV SF/kaiju/superhero tokusatsu, dan Seri Ultra ke-4.Eiji Tsuburaya awalnya ditujukan untuk Seri Ultra untuk dibatalkan dengan seri 1967 Ultra Seven (Urutora Sebun, 1967), tapi Ultraman (Urutoraman, 1966) terbukti terlalu populer karakter untuk dijaga. Setelah kematian Eiji Tsuburaya pada tahun 1970, anaknya Hajime Tsuburaya (yang mengambil alih Tsuburaya Productions sampai kematiannya sendiri pada tahun 1973) menghidupkan kembali Seri Ultra dengan Return of Ultraman.Ditampilkan dalam acara ini adalah Ultraman baru yang diberi nama \"Ultraman Baru\" (新ウルトラマン Shin Urutoraman?), atau hanya \"Kembalinya Ultraman\" (帰ってきたウルトラマン Kaettekita Urutoraman?), seperti judul acara. Pada tahun 1984, bagaimanapun, ia telah berganti nama \"Ultraman Jack\" (ウルトラマンジャック Urutoraman Jakku?) karena masalah perizinan, setelah Tsuburaya dan Bandai (yang baru saja membeli lisensi mainan Ultraman di Jepang) mengadakan kontes untuk anak-anak untuk memilih nama baru untuk Ultraman ini. Meskipun ia disebut \"Ultraman Jack\" untuk lisensi masuk dan keluar dari Jepang, ia masih kadang-kadang disebut sebagai \"Ultraman Baru\"/\"Kaettekita Ultraman\", oleh beberapa penggemar (dan juga di beberapa sumber resmi). Perubahan ini dilakukan karena keputusan menit terakhir karena rencana semula untuk seri ini adalah untuk Ultraman asli untuk kembali ke Earth untuk melanjutkan perang melawan alien dan monster.",
            "1971",
            "Hajime Tsuburaya",
            "https://static.wikia.nocookie.net/ultramananthology/images/8/82/Ultraman_Jack.png/revision/latest?cb=20220430183924",
            "https://static.wikia.nocookie.net/ultra/images/a/ab/Hajime_Tsuburaya_1.png/revision/latest?cb=20230220163905"
        ),

        Ultra(
            "3",
            "Ultra Seven",
            "Ultraseven (ウルトラセブン, Urutora Sebun) adalah seri televisi fiksi ilmiah tokusatsu Jepang oleh Eiji Tsuburaya. Serial ini adalah angsuran ketiga dalam Seri Ultra dan diproduksi oleh Tsuburaya Productions. Serial ini ditayangkan di Sistem Penyiaran Tokyo dari 1 Oktober 1967 hingga 8 September 1968.Dalam waktu yang tidak terlalu lama lagi, Bumi mendapati dirinya terus-menerus di bawah serangan dari ancaman makhluk luar angkasa. Untuk melawan mereka, Angkatan Pertahanan Terestrial membentuk Ultra Garrison, sebuah tim yang terdiri dari enam anggota elit yang menggunakan kendaraan dan persenjataan berteknologi tinggi. Sosok yang bergabung dengan pertarungan mereka adalah Dan Moroboshi si misterius yang diam-diam adalah alien dari Tanah Cahaya di Nebula M-78 dan berubah menjadi bentuk alien aslinya, Ultraseven, di saat krisis.",
            "1967",
            "Eiji Tsuburaya",
            "https://resizing.flixster.com/F40mkTT06dFdLhtbbpGzfr_bnig=/206x305/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p520147_b_v10_ac.jpg",
            "https://wikizilla.org/w/images/8/83/Tsuburaya_Smile.jpg"
        ),
        Ultra(
            "4",
            "Ultraman Ace",
            "Ultraman Ace (ウルトラマンエース Urutoraman Ēsu?), juga dikenal sebagai Ultraman A (ウルトラマンA Urutoraman A?), adalah Ultra Brothers kelima untuk sampai di bumi. Dia adalah yang pertama, dan sejauh ini, hanya Ultra yang memiliki dua hosti manusia pada saat bersamaan. Dia tiba di Bumi untuk menjaganya dari dalang alien yang jahat Yapool. Saat Ace tiba di Bumi, dia bergabung dengan seorang pria, Seiji Hokuto, dan wanita, Yuko Minami, untuk mengubah kepribadiannya, memberi Ace keberanian pria dan cinta seorang wanita untuk perdamaian.Yapool, makhluk antar dimensi, mencari planet Bumi dan mencoba menaklukkannya dengan kampanye yang melibatkan eksperimennya yang dikenal sebagai Monster Mengerikan. Senjata super pertama yang dikirim ke Bumi, Verokron, menghancurkan sebuah kota dan melawan TAC, unit pasukan khusus yang diciptakan oleh Pasukan Bela Diri untuk mempertahankan Bumi dari Kaiju. Dua korban malang Verokron adalah Seiji Hokuto dan Yuko Minami. Lima Ultra Brothers pertama, Ultraman, Zoffy, Ultraseven, Ultraman Jack, dan Ultraman Ace, memutuskan untuk menghidupkan kembali duo tersebut karena mencoba membantu anak-anak kecil menjauh dari Monster Mengerikan dan melawan pasukan Yapool.\n" +
                    "\n" +
                    "Ace memutuskan untuk menjadi orang yang pergi karena mereka berdua menjadi tuan rumahnya. Yapool tidak hanya menggunakan Monster-Monster Mengerikan, tetapi juga merekrut alien lain, manusia yang menjual jiwa mereka kepadanya untuk dimiliki Monster-Monster Mengerikan, dan bahkan dirinya sendiri, untuk membunuh Ace dan TAC hanya untuk dijatuhkan dalam kekalahan mutlak. Setelah penghancuran salah satu Monster Mengerikan tertua di Yapool, Lunaticks, Minami mengungkapkan bahwa dia adalah salah satu penduduk asli terakhir dari bulan dan memberikan Cincin Ultranya kepada Seiji karena dia harus pergi, tetapi berjanji akan kembali sesekali.\n" +
                    "\n" +
                    "Sejak saat itu, Seiji menjadi satu-satunya pembawa acara Ace dan upaya mereka tetap sama. Yapool menjadi putus asa dengan menggabungkan tubuh beberapa Monster Mengerikan terpilih untuk menciptakan Raja Jumbo namun dia gagal dan membuat Ace terbang ke dunia asalnya di Nebula M78. Sejak saat itu, Ace muncul untuk membantu para Ultra di saat mereka membutuhkan. Ultraman Ace masih mempertahankan koneksi ke Seiji sebagai hosti manusianya, seperti yang terlihat dalam serial Ultraman Mebius dan film berikutnya.",
            "1972",
            "Eiji Tsuburaya",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrzVV9q5AlR3tg3POaV8Y2DAeUejDH5EgCBA&usqp=CAU",
            "https://wikizilla.org/w/images/8/83/Tsuburaya_Smile.jpg"
        ),

        Ultra(
            "5",
            "Ultraman Taro",
            "Ultraman Taro (ウルトラマンタロウ Urutoraman Tarō?), juga dikenal sebagai Ultraman No.6 (ウルトラマンNo.6 Urutoraman Nanbā 6?), dan Guru Taro oleh Ultra Brothers, adalah putra Ayah Ultra dan Ibu Ultra. Ia dilatih sejak ia masih muda, untuk menjadi Ultraman paling terkuat. Dia saat ini tinggal sebagai guru di Tanah Cahaya, di mana dia mengajar para pejuang muda dan dewasa sama bagaimana berperang di Ultra Coliseum.\n" +
                    "\nUltraman Taro pertama kali muncul di Ultra Coliseum menyaksikan murid-muridnya berlatih untuk menjadi Pejuang Ultra ketika mereka tumbuh dewasa. Beberapa saat kemudian, setelah Ultraman Belial dibebaskan, murid-murid Taro semua berperang melawan Belial di Penjara Luar Angkasa, dengan Belial dengan mudah mengalahkan mereka semua. Tiba-tiba Taro muncul dan mulai bertarung dengan Belial. Taro menggunakan Storium Ray, tetapi Belial menghindarinya, dan Taro dengan cepat meraih Belial dan mereka berdua jatuh ke Tanah Cahaya. Setelah mereka berdua menabrak bumi, Belial mengungkapkan bahwa Taro dikalahkan olehnya, dan melemparkannya pingsan ke tanah. Belial kemudian bertarung melawan setiap Pejuang Ultra, dan para Ultra Brother, dan setelah dia mengalahkan Ayah Ultra dan Ibu Ultra, dia akan menembak mereka untuk membunuh mereka. Tapi ketika Belial menembakkan pancarannya, Taro muncul dan hampir mengorbankan dirinya untuk menyelamatkan ayah dan ibunya dari kematian. Belial mengambil Plasma Spark, sehingga menyebabkan kematian Tanah Cahaya, tetapi Ultraman Taro mengelola untuk mencegah kehancuran Tanah Cahaya dengan menyimpan cahaya yang tersisa.\n" +
                    "\n" +
                    "Beberapa waktu kemudian, Ultraman, Ultraseven dan Mebius muncul untuk mengembalikan bentuk Ultra mereka, mereka melihat Taro benar-benar membeku karena kematian Tanah Cahaya. Setelah Taro melihat mereka, dia mengembalikan bentuk Ultra mereka, dan mengatakan bahwa cahaya ini adalah \"kesempatan terakhir kita\", dan dia kemudian jatuh ke dalam trans beku sementara masih menggendong cahaya yang tersisa. Ultraman, Ultra Seven, dan Mebius kemudian pergi ke Menara Plasma Spark untuk mendapatkan kembali energi yang cukup untuk melawan Belial. Taro dihidupkan kembali untuk sesaat, tapi dia masih membeku dan memberikan trio Ultra energi yang tersisa sebelum kembali ke keadaan tertidurnya.",
            "1973",
            "Eiji Tsuburaya",
            "https://www.themoviedb.org/t/p/original/bLnb77enw2zkHV66EuLdJKIjDrU.jpg",
            "https://wikizilla.org/w/images/8/83/Tsuburaya_Smile.jpg"
        ),
        Ultra(
            "6",
            "Ultraman Leo",
            "Ultraman Leo (ウルトラマンレオ, Urutoraman Reo?) adalah Ultra asing ke Tanah Cahaya, bukannya memanggil dari Planet L77 dari konstelasi Leo yang jatuh, dimana dia dan adiknya Astra adalah royalti. Setelah planetnya dihancurkan oleh Alien Magma I dan kaiju Giras kembar-nya, dia pergi ke Bumi, berniat untuk menjadikannya rumah kedua. Sementara di sana, ia bercampur dengan masyarakat manusia Gen Ohtori, dan menjadi instruktur gym di klub kebugaran untuk anak-anak. Tapi, saat Alien Magma yang menghancurkan L77 datang untuk menaklukkan Bumi, dia terpaksa mengambil tindakan. Leo bertemu Ultraseven saat bertarung awal melawan Alien Magma, dan menjadi Ultra Crusader pertama Bumi yang tidak berasal dari Tanah Cahaya. Tidak seperti kebanyakan Ultra sebelumnya yang mengunjungi Bumi, gaya bertarung Leo mengkhususkan diri pada seni bela diri yang memberinya kemampuan fisik jauh lebih hebat daripada Ultra lain yang diketahui. Meskipun berasal dari luar negeri, dia, bersama Astra, dengan mudah diterima di dalam panteon Ultra Brothers. Selama masa jabatannya di Bumi, Leo dan Tujuh menjadi sangat dekat, dan karena itulah, Seven akhirnya mempercayakan pelatihan untuk anaknya Ultraman Zero kepada Leo dan Astra.Leo awalnya tinggal di Nebula L-77 di konstelasi Leo, bersama dengan anggota spesiesnya termasuk adiknya Astra dan hewan peliharaannya Ron, yang mirip dengan makhluk di Nebula M78. Namun, Nebula L-77 dihancurkan setelah mengamuk perang dengan Alien Magma. Akibatnya, Leo, Astra dan Ron menjadi satu-satunya yang selamat dari Nebula L-77.Alien Magma kemudian pergi ke Bumi dengan Giras Merah dan Hitam. Ultraseven dikirim untuk mencegat mereka tetapi dikalahkan karena monster terlalu kuat untuk Seven. Leo tiba di Bumi dan segera mengalahkan monster tetapi Alien Magma terpaksa melarikan diri. Leo kemudian membuat bentuk manusia untuk dirinya sendiri di bawah alias Gen Ohtori. Setelah Ultra Eye Seven rusak, dia tetap di Bumi. Tujuh saat Dan membentuk MAC dengan dia sebagai kapten sementara Leo bergabung sebagai anggota.",
            "1974",
            "\tShigemitsu Taguchi",
            "https://pbs.twimg.com/media/FFlgrLRVIAQ0qCk.jpg",
            "https://static.wikia.nocookie.net/ultra/images/a/a4/Shigemitsu_Taguch.jpeg/revision/latest?cb=20230309143036"
        ),
        Ultra(
            "7",
            "Ultraman Tiga",
            "Ultraman Tiga (ウルトラマンティガ Urutoraman Tiga?) adalah Ultra yang memulai debutnya pada tahun 1996, dan merupakan pahlawan Ultra pertama yang tampil dalam serial televisi panjang sejak tahun 1981, yang mengakhiri hiatus 15 tahun dari waralaba Ultraman sejak berakhirnya Ultraman 80.\n" +
                    "\n" +
                    "Diatur di alam semesta yang berbeda dari semua seri sebelumnya, Ultraman Tiga memperkenalkan pembaruan baru dan radikal terhadap karakter Ultraman untuk generasi pendengar baru; terutama dia menjadi Ultraman pertama dengan beberapa mode tempur dan warna bukan merah (Ungu dan Emas). Dia juga dianggap salah satu entri paling populer dalam franchise ini, memiliki lebih banyak eksposur di TV dan film dibandingkan dengan pahlawan Heisei Ultra lainnya (seri 52 episode, lima tim film pada tahun 1998, 1999, 2008, 2015, 2016 dan dua sekuel langsung pada tahun 2000 dan 2001).Tiga pernah menjadi pemimpin Raksasa Gelap, dan merupakan perusak besar, tapi sejak itu melepaskan sifat bayangannya demi cahaya dan menyalakan rekan-rekannya dengan menyegelnya dalam bentuk patung di balik segel besar dan mengambil alih kekuatan mereka. Dia akhirnya menjadi yang terkuat dari trio pahlawan Ultra di antara koloni Ultra yang melindungi peradaban kuno di Bumi. Tiga adannd timnya menyelamatkan peradaban dari bencana yang tak terhitung jumlahnya. Setelah tugas mereka selesai, mereka dibaringkan untuk beristirahat di dalam piramida raksasa sampai Bumi membutuhkannya lagi. Esensi mereka berangkat menuju Tanah Cahaya meninggalkan replika fisik wujud mereka untuk generasi masa depan.Sebuah legenda kuno sebuah desa menyatakan bahwa sejak lama desa tersebut diserang oleh monster yang mengerikan namun diselamatkan oleh raksasa. Setelah pertempuran itu raksasa itu kembali ke gunung dan menghilang bersama orang-orang di desa yang menyembah ingatannya, Raksasa Cahaya.\n" +
                    "\n" +
                    "Bertahun-tahun kemudian, pemburu rakasa yang mengembara menemukan Spark Lens yang legendaris di samping monster yang baru saja dia bunuh, tidak tahu apa itu dia menyimpannya tapi ketika dia mendekati sebuah desa yang diserang oleh monster Spark Lens mulai menggigil. Pertahanan kayu desa tidak cocok untuk monster dan desa tersebut rusak parah dengan para pembela desa yang berusaha menghadapinya dengan tombak. Ternyata monster itu 'dipanggil' untuk waktu itu oleh seorang penyihir yang ingin mencegah kebangkitan Tiga dengan menghancurkan piramida emas dimana jenazahnya terbaring ngeri (yang sama Daigo akan masuk dan menemukan Ultraman Tiga di Ultraman Tiga Episode 1).\n" +
                    "\n" +
                    "Ketika Tsubasa, anak Daigo dan Rena yang dikirim ke masa lalu oleh sang penyihir, dia melihat Spark Lens yang jatuh dari tas pemburu monster itu. Dia langsung menyadari bahwa itu mirip dengan yang digunakan ayahnya untuk berubah menjadi Tiga. Dia mencengkeramnya sebelum pemburu monster itu bisa menolak dan berubah menjadi Tiga. Monster itu dikalahkan dengan mudah tapi pada akhirnya Tiga lenyap saat Tsubasa tidak ditakdirkan untuk benar-benar memanfaatkan kekuatannya, biarpun dia memiliki genetika yang benar, dan seluruh desa hancur. Kemudian Amui; seorang anak laki-laki yang berteman dengan Tsubasa, mengatakan kepada desa bahwa dia melihat raksasa cahaya itu, tapi tidak ada yang mempercayainya sampai para pembela menyatakan bahwa mereka juga melihat Tiga. Mendengar ini salah satu pelihat di desa tersebut mengklaim bahwa ramalan itu menjadi kenyataan dan segera seseorang di desa mereka adalah orang yang membangunkan Tiga. Meskipun Tiga mengalahkan monster pertama penyihir itu, dia mengirim monster terkuat dan dua acolytesnya untuk mencoba dan menghancurkan piramida lagi. Penduduk desa, dengan bantuan dari elit desa lain, dan pemburu rakasa itu melawan dua acolytes namun Tsubasa gagal mengalahkan monster Dogouf, yang mengalahkan Tiga dengan mudah.\n" +
                    "\n" +
                    "Tsubasa kembali ke bentuk manusia yang kelelahan dan Spark Lens kuno hampir diinjak-injak oleh Dogouf namun Amui menyimpannya dan ternyata adalah orang yang akan memenuhi nubuatan tersebut. Dia menggunakan perangkat untuk berubah menjadi Tiga yang akhirnya menghentikan Dogouf dengan menggunakan langkah penyelesaian Tiga Power Type setelah pertempuran yang sulit. Tsubasa kemudian memasang jetnya dan kembali ke masa depan dengan Tiga saat dia mengawasi desa itu. Meskipun desa tersebut lenyap pada waktunya, tanah tersebut kemudian dikenal sebagai Tiga, sebuah petunjuk penting yang memungkinkan GUTS menemukan piramida di tempat pertama.",
            "1996",
            "Issei Futamata",
            "https://static.wikia.nocookie.net/ultra/images/1/1e/Tiga_Ultra_Flare.jpg/revision/latest?cb=20200428163226",
            "https://static.wikia.nocookie.net/ultra/images/4/47/IsseiFutamata.jpg/revision/latest?cb=20180325145119"
        ),
        Ultra(
            "8",
            "Ultraman Dyna",
            "Ultraman Dyna (ウルトラマンダイナ Urutoraman Daina?) adalah protagonis Seri TV Ultraman Dyna es un gigante de la luz que es diferente a Ultraman Tiga\n" +
                    "\n" +
                    "Dyna akhirnya menemukan dirinya berada di dalam semesta Nebula M78. Kemudian, atas permintaan ZAP Spacy Pendragon Crew, dia melakukan teleport ke Makam Monster, di mana dia bertemu dengan Ultraman asli dan membantu Ultra mengalahkan kejahatan rencana pertama Ultraman Belial untuk menguasai alam semesta.\n" +
                    "\n" +
                    "Dalam film Ultraman Saga itu terungkap ia melakukan perjalanan ke alam semesta lain, dan di sampingn Ultraman Cosmos dan Ultraman Zero, mengalahkan Alien Bat jahat dan wayangnya Hyper Zetton.Ultra adalah raksasa cahaya yang ditemukan oleh peserta pelatihan di Regu Pelatihan ZERO, Shin Asuka. Setelah Asuka direkrut menjadi Super GUTS, Pangkalan Mars TPC diserang oleh Sphire. The Ultra kemudian memperkenalkan dirinya secara luas kepada teman-temannya kemudian dengan menghancurkan monster Sfera: Darambia, dengan hanya mentransformasikannya. Namun, ia kemudian akan memamerkan keahliannya dengan mengalahkan monster yang baru dibuat: Neo-Darambia. Beberapa anggota yang lebih tua dari kontingen TPC di koloni percaya bahwa Ultraman Tiga, kembali dan diperbarui. Para perwira yang lebih tua, bagaimanapun, menyadari bahwa itu bukan Tiga, tetapi mungkin wali lain seperti dia. Asuka sebagai Ultraman menghadapi Darambia dan akhirnya mengalahkannya.\n" +
                    "\n" +
                    "Segera, ketika Giralen, monster lain yang diciptakan oleh Sphere menyerang Pangkalan Super GUTS, Asuka berubah menjadi Ultra sekali lagi dan menyelesaikan monster dengan Revolium Ray. Setelah menyaksikan seluruh pertempuran, Mai, operator tim memutuskan untuk menamai Ultraman sebagai Ultraman Dyna. Kemudian, setelah pertarungannya sebagai Dyna dengan Grossyna, Asuka menjadi dewasa, menyadari sepenuhnya tanggung jawabnya sebagai anggota Super GUTS. Banyak dari monster ini mengajarkan pelajaran Asuka dan memberikan kenangan untuk orang dewasa muda, yang memulai mottonya \"Jangan pernah menyerah!\"",
            "1997",
            "Yuji machi",
            "https://www.themoviedb.org/t/p/original/41hugdtFPdnlU1OPGpqpcVI0IDF.jpg",
            "https://static.wikia.nocookie.net/ultra/images/6/60/Yuji_Machi_2.jpg/revision/latest?cb=20220723004052"
        ),
        Ultra(
            "9",
            "Ultraman gaia",
            "Ultraman Gaia (ウルトラマンガイア Urutoraman Gaia?) adalah makhluk Ultra Gelombang Heisei Pertama Tsuburaya Productions, diciptakan oleh setelah hiatus 15 tahun dari waralaba Ultraman. Dia adalah penerusnya Ultraman Tiga dan Ultraman Dyna di gelombang Heisei yang pertama dari kebangkitan Seri Ultra. Bentuk utama pertamanya adalah Versi 1, dan dia tidak mampu mengubah bentuk seperti dua Ultraman Heisei sebelumnya. Kemudian, ia mendapatkan Versi 2 dan Versi Supreme dari cahaya Ultraman Agul.Bentuk Supreme Adalah bentuk Saat Gaia menggunakan Kekuatan ultraman Agul Secara sepenuhnya.Ultraman Gaia terjadi di alam semesta yang lain, yang berbeda dari dunia Ultraman era Showa (Ultraman sampai Ultraman 80), serta dunia Ultraman Tiga dan Ultraman Dyna. Dalam keberangkatan dari sebagian besar seri lainnya, ada dua Ultraman sebagai karakter utama. Mereka memiliki filosofi yang bertentangan dalam hal membela Bumi dari sebuah entitas kosmik misterius, jahat, dan sangat cerdas.\n" +
                    "\n" +
                    "Acara ini juga berbeda dari seri Ultra yang sebelumnya, bahwa tim dukungan, XIG, memiliki lebih banyak personil dari tim pertahanan dalam seri sebelumnya.\n" +
                    "\n" +
                    "Dalam seri ini, Ultraman Gaia adalah Ultraman utama, tetapi Ultraman Agul membuat banyak penampilan. Mereka sering bertentangan satu sama lain pada awal seri. Filsafat berbeda seperti warna kulit mereka. Tidak seperti Gaia, Agul berwarna biru. Gamu Takayama, wujud manusia dari Ultraman Gaia, percaya bahwa Gaia ada untuk menyelamatkan Bumi dan umat manusia. Di sisi lain, Hiroya Fujimiya, wujud manusia dari Ultraman Agul, percaya Agul menjadi mekanisme pertahanan alami Bumi. Fujimiya pada awalnya lebih tertarik dalam melindungi hanya planet itu sendiri, bahkan mengorbankan manusia (maka bertarung sesekali dengan Gaia). Tapi ini dihentikan setelah Gaia dan Agul bekerja bersama untuk menghadapi monster yang lebih kuat.Cerita terjadi pada tahun 2000. CRISIS, superkomputer yang dikembangkan oleh Alchemy Stars (jaringan global pemuda jenius yang lahir selama tahun 1980), memprediksi sekitar 1996-1997 bahwa Bumi dan umat manusia akan dibinasakan oleh sesuatu yang dikenal sebagai \"Radical Destruction Bringer\". Teknologi yang dikembangkan oleh Alchemy Stars digunakan untuk membentuk sebuah organisasi pertahanan internasional yang dikenal sebagai Geocentric Universal Alliance against the Radical Destruction (GUARD). Hal ini dilakukan secara diam-diam untuk menghindari kepanikan di seluruh dunia. eXpanded Interceptive Guardians (XIG) adalah tim pertahanan Bumi di bawah pimpinan GUARD. Mereka beroperasi di markas yang mengambang di langit yang dikenal sebagai Aerial Base.\n" +
                    "\n" +
                    "Gamu Takayama, pemuda berumur 20 tahun, adalah seorang ilmuwan dan anggota Alchemy Stars yang bertemu dengan Ultraman Gaia saat bereksperimen dengan realitas virtual. Ia melakukannya dengan tujuan menemukan rahasia kehendak Bumi, kemudian bersatu dengan Ultraman Gaia untuk melawan berbagai monster yang mengancam keselamatan Bumi. Selama pertempuran, ia bertemu dengan Ultraman Agul, yang wujud manusianya adalah Hiroya Fujimiya, mantan anggota Alchemy Stars. Keduanya bertarung satu sama lain karena filosofi mereka yang berbeda tentang melindungi Bumi. Tetapi akhirnya mereka memahami perbedaan mereka berdua untuk melawan musuh bersama-sama.",
            "1998",
            "Chiaki J. Konaka",
            "https://tsuburaya-prod.com/wp-content/uploads/2021/11/GAIA1765_02.jpg",
            "https://static.wikia.nocookie.net/ultra/images/5/5c/Chiaki_J_Konaka.png/revision/latest?cb=20230110104237",
        ),
        Ultra(
            "10",
            "Ultraman Cosmos",
            "Ultraman Cosmos (ウルトラマンコスモス Urutoraman Kosumosu?) adalah Ultra lembut dari galaksi yang tidak diketahui. Dia dikenal dengan gaya bertarung yang tenang dan lembut, dan belas kasihnya terhadap monster. Dia pertama kali pergi ke Bumi untuk melindungi dari invasi Alien Baltan Basical. Selama waktunya di Bumi ia berteman dengan seorang anak muda bernama Musashi Haruno, yang memberikannya kristal biru untuk memanggilnya jika anak itu membutuhkan pertolongan. Setelah Cosmos menangani invasi Baltan, dia meninggalkan Bumi selama sepuluh tahun sebelum bersatu kembali dan bergabung dengan Musashi yang sekarang berusia 19 tahun, yang telah menjadi anggota pasukan pertahanan Bumi EYES, sehingga mereka bisa memerangi Chaos Header. Setelah menghabiskan waktu sekitar satu tahun di Bumi untuk melindungi semua bentuk kehidupan di samping Tim EYES melawan Chaos Header, Cosmos akhirnya menukarkan Chaos Header dari kegelapan saat berada, dan kembali ke ruang di samping Chaos Header 0 yang baru, meninggalkan Musashi ke bekerja menuju hari dimana manusia dan kaiju akan hidup bersama dalam damai.\n" +
                    "\n" +
                    "Selama acara film Ultraman Cosmos kedua, setelah satu tahun yang lalu sejak peristiwa serial TV Ultraman Cosmos, Cosmos kembali ke Bumi dan sekali lagi bergabung kembali dengan Musashi untuk memerangi kejahatan Sandros. HNamun, alien luar angkasa terbukti lebih dari sekadar yang bisa ditangani Cosmos, dan ini adalah kedatangan tepat waktu dari Pejuanh Ultra, Ultraman Justice yang memungkinkan Cosmos dan Musashi mengalahkan Sandros.\n" +
                    "\n" +
                    "Dalam acara final film Ultraman Cosmos, Cosmos dan Justice bergabung bersama untuk membentuk Super Ultraman; Ultraman Legend, yang disebut oleh Alien Gyashi sebagai pejuang terkuat di alam semesta.Seorang makhluk asing yang menjaga Bumi, ia mengikuti Alien Baltan melalui ruang angkasa saat ia mencoba untuk membuat jalannya menuju Bumi. Bertemu dengan itu dan dengan cepat melawannya, para raksasa bentrok. Berjuang untuk beberapa waktu dan pukulan perdagangan, segera kedua prajurit jatuh dari langit. Sementara Baltan bergerak di bawah tanah, Cosmos terluka dan kehabisan tenaga. Di pintu kematian, tampaknya pahlawan itu sudah selesai sampai seorang bocah kecil menemukannya. Musashi Haruno berhasil menghidupkan kembali sang pahlawan dengan memantulkan sinar matahari ke lampu sorot di kepalanya.\n" +
                    "\n" +
                    "Dihidupkan kembali, Cosmos membawa bocah lelaki itu untuk menunggang pemandangan sebelum memberinya permata kecil yang berisi kekuatan untuk memanggil sang pahlawan. Kata-kata perpisahannya adalah \"Orang yang kuat adalah orang yang berani\". Selama serangan Basical di kota, Musashi berusaha keras untuk memanggilnya tetapi tidak bisa. Dia dipaksa untuk menonton saat alien menghancurkan semuanya di jalannya.",
            "2002",
            "Tsuburaya Production",
            "https://static.wikia.nocookie.net/ultra/images/9/96/Poster_The_First_Contact.jpg/revision/latest?cb=20180123105229&path-prefix=id",
            "https://en.tsuburaya-prod.co.jp/wp-content/themes/tsuburaya_renewal/old-assets/img/ogp.png"
        ),
        Ultra(
            "11",
            "Ultraman Nexus",
            "Ultraman Nexus (ウルトラマンネクサス Urutoraman Nekusasu?) adalah bentuk devolusi kedua Ultraman Noa, dan merupakan bentuk asumsi Dunamist setelah menggunakan Evoltruster. Membintangi Ultraman Nexus, ceritanya diwakili sebagai fase akhir Ultra N Project. Setelah berevolusi dari Ultraman the Next, Nexus akan muncul kembali pada tahun 2008 untuk melawan gelombang serangan Space Beast, perlahan tumbuh dalam kekuatan setelah terikat dengan beberapa Dunamist dan akhirnya mendapatkan kembali bentuknya yang telah lama hilang dalam pertempuran dengan Zagi.\n" +
                    "\n" +
                    "Meskipun Noa adalah identitas aslinya, ia membuat sebagian besar penampilan masa depannya sebagai Nexus di Seri Ultra berikutnya.Ketika dunia terkejut dari bencana Space Beast pertama,Noa mendasarkan dirinya di Bumi dan berevolusi lebih jauh menjadi Ultraman Nexus. Selama bertahun-tahun yang berlalu hingga 2008 Masehi, sebuah organisasi global rahasia yang dikenal sebagai Terrestrial Liberation Trust telah dibentuk untuk mempertahankan Bumi dari ancaman Space Beasts. Pada saat yang sama, mereka bertanggung jawab untuk menghilangkan ingatan publik akan Ultraman atau Space Beasts sejak Bencana Shinjuku 2004.Hal ini dilakukan untuk mencegah terjadinya kepanikan global, yang akan menciptakan kondisi ideal bagi lebih banyak Space Beasts untuk muncul dan memberi makan pada ketakutan umat manusia.Noa sendiri telah memulai tindakannya sendiri untuk melindungi dunia dari Zagi dan kaki tanganya sebagai Ultraman Nexus, dan segera memilih Jun Himeya, seorang mantan fotografer perang yang mengalami kesalahan orang yang selamat dari ketidakmampuan menyelamatkan seorang anak yatim bernama Sera. Nasib dipilih sebagai Dunamist membawanya untuk menganggapnya sebagai hukuman sendiri atas dosa masa lalunya. Selama menjadi host untuk Nexus, ia pertama kali dilihat sebagai Space Beast oleh sebagian besar Night Raiders, sementara Kazuki Komon menjadi teman setelah diselamatkan dari Pedoleon dan beberapa Space Beast sesudahnya. Komon juga merahasiakan identitas Himeya sebagai rahasia Ultraman dari atasannya dan sering berdebat  dengan atasan langsung Nagi atas masalah apakah Ultraman harus dipercaya atau tidak.",
            "2005",
            "Keiichi Hasegawa",
            "https://upload.wikimedia.org/wikipedia/en/thumb/9/9d/UrutoramanNekusasu.jpg/220px-UrutoramanNekusasu.jpg",
            "https://static.wikia.nocookie.net/ultra/images/a/a6/Keiichi_Hasegawa.png/revision/latest?cb=20221216100856"
        ),
        Ultra(
            "12",
            "Ultraman Mebius",
            "Ultraman Mebius (ウルトラマンメビウス Urutoraman Mebiusu?) dipilih sebagai pelindung baru Bumi dan merupakan Ultra kesepuluh dari Tanah Cahaya. Dia saat ini tinggal di Tanah Cahaya, membantu Ultra Brothers.Dikatakan dijadikan adik bongsu adik beradik ultra , digelar (Rookie) di angkasa garrison yang bermaksud adik kecil .Dengan kata lain keluarga ayah ultra dijadikan keluarga angkat olehnya.Dia lebih rapat dengan ultraman taro sejak muda lagi, dan membuatkan ayah ultra menjadikan taro sebagai guru kepada mebius.\n" +
                    "\n" +
                    "Mengikut undang-undang tanah cahaya,sebarang gelaran/pangkat tinggi perlu dihormat dan dipanggil secara waktu tertentu.Iaitu perlu dipanggil saat bekerja atau saat genting ,akan tetapi pada sesi keluarga/Waktu tidak genting ,tidak perlu dipanggil.Sebagai contohnya,pangkat ultraman taro adalah guru kepada mebius ,maka dia perlu memanggil taro sebagai (master taro),namun saat sesi keluarga/tidak genting, mebius memanggilnya (abang taro).\n" +
                    "\n" +
                    "Dia dianggap salah satu ultra terkuat dari ultra brother mahupun galaksi.Dia bersifat baik hati ,naif dan rendah diri.Disebabkan sikap terlalu naif dan rendah diri terkadang mebius berapa lemah dalam bertarung,oleh itu abang-abangnya akan membantu dan menaikkan keyakinannya semula.\n" +
                    "\n" +
                    "Mebius juga digelar adik kesayangan oleh disebabkan series episodnya dipenuhi bantuan oleh abangnya(ultra brother).Hal itu boleh dikatakan benar juga kerana abang-abangnya sangat risau akan mebius yang berada di bumi, lagi-lagi ultraman taro yang mahu menjadi yang pertama membantu mebius, mahupun ayah ultra dan ibu ultra yang sentiasa mengawasi mebius dari jauh .\n" +
                    "\n" +
                    "Namun asal usulnya yang benar tidak diketahui.",
            "2006",
            "\tMasanao Akahoshi",
            "https://upload.wikimedia.org/wikipedia/en/thumb/4/4a/UltramanMebiusu.jpg/220px-UltramanMebiusu.jpg",
            "https://static.wikia.nocookie.net/ultra/images/5/5c/Masanao_Akahoshi.png/revision/latest?cb=20230322031722",
        ),
        Ultra(
            "13",
            "Ultraman Zero",
            "Ultraman Zero (ウルトラマンゼロ Urutoraman Zero?) adalah anak laki-laki Ultraseven. Dia dilatih di bawah Ultraman Leo setelah dia diusir dari Tanah Cahaya oleh ayahnya karena mencoba mengambil Plasma Spark untuk dirinya sendiri. Pelatihannya akhirnya menyebabkan penebusannya dalam pertempuran dengan Belial. Dia dianggap salah satu Ultra terkuat sepanjang sejarah.Dulu, Zero dikenal sebagai pejuang muda dengan potensi tak terbatas namun tidak memiliki kesadaran akan asal sebenarnya. Diinginkan untuk mendapatkan lebih banyak tenaga, dia mencoba untuk mengambil Plasma Spark namun dihentikan oleh Ultraseven, diikuti oleh sisa Ultra Bersaudara yang menyeretnya keluar dari menara.\n" +
                    "\n" +
                    "Zero pertama kali dilihat memakai baju besi Techtor Gear dan berlatih dengan Ultraman Leo di K76, planet yang dia kirim setelah diusir. Ketika Pigmon berada dalam bahaya, Zero memutuskan untuk menyelamatkannya daripada melanjutkan pertempurannya dengan Leo. Leo dan Ultraman King kemudian mengungkapkan kepadanya bahwa melindungi kehidupan adalah tujuan Ultra. Ketika Seven mengasingkan dirinya, dia sebenarnya menyelamatkan Zero dari menyentuh Plasma Spark dan dengan demikian mencegahnya dari takdir yang mirip dengan Ultraman Belial Ultraman Belial.\n" +
                    "\n" +
                    "Saat Eye Slugger Seven dikirim sebagai S.O.S. kepada K76, King dan Leo mengungkapkan kepada Zero bahwa Seven adalah ayahnya. King mengumumkan Zero menebus dan membebaskannya dari baju besinya sehingga dia bisa ikut berperang melawan Belial. Zero tiba hanya untuk memiliki Seven korban luka yang tewas dalam pelukannya. Ultra muda sangat marah dan menghancurkan sisa-sisa 100 Monster Tentara Belial dan berperang melawan Belial sendiri, yang tampaknya menghancurkannya setelah pertempuran yang panjang.Tapi saat Belial kembali sebagai Beryudora, dia membawa bantuan dari Ultra Bersaudara yang tersisa, Leo, Astra, Ultraman Dyna, Rei, EX Gomora, dan semua ZAP SPACE untuk menghancurkan Belial. Setelah Plasma Spark dikembalikan, Zero bersatu kembali dengan ayahnya yang baru kembali.",
            "2009",
            "\t\n" +
                    "Koichi Sakamoto",
            "https://i.pinimg.com/736x/8c/68/99/8c6899e13bff9c5790dff9a736b9b8b6.jpg",
            "https://upload.wikimedia.org/wikipedia/en/thumb/e/ee/Koichi_Sakamoto.JPG/200px-Koichi_Sakamoto.JPG"
        ),
        Ultra(
            "14",
            "Ultraman Max",
            "Ultraman Max (ウルトラマンマックス Urutoraman Makkusu?) adalah Ultra dari waktu Nebula M78 alternatif yang terjadi sekitar empat puluh tahun setelah kejadian yang pertama seri TV Ultraman. Dia juga diyakini membanggakan kecepatan alami Ultra tercepat dari Tanah Cahaya. Mitra utamanya M78 telah membuat beberapa penampilan singkat dalam trilogi film Ultraman Zero.Serial ini sempat diwarnai oleh isu bahwa kisahnya adalah sambungan dari kisah Ultraman di era Showa dan juga anggota Space Garrisona. Hal ini dikuatkan dengan desain Max yang secara fisik mirip dengan Ultraseve dan Ultraman Taro, begitu pula dengan jurus-jurusnya. Selain itu, monster lama seperti Baltan dan monster masa lalu yang sering muncul dalam era Showa juga muncul kembali dalam serial ini. Namun, Tsuburaya menepis isu tersebut menjelang episode-episode terakhir Max, bahwa kenyataannya Max tidak memiliki hubungan dengan serial Ultraman manapun yang pernah muncul. Penonton Jepang pun bertanya-tanya mengapa total episode Max kurang dari 50, padahal respon dan ratingnya membaik.\n" +
                    "\n" +
                    "Max diproduksi dengan maksud sebagai batu loncatan dari Ultraman Nexus, yang konsep ceritanya melenceng jauh, sebelum menginjak kembali ke era Showa. Bisa dibilang kisah dan konsep Max berada di persimpangan. Sebelum masa tayang Max habis, serial penggantinya yaitu Ultraman Mebius, yang justru kejutan yang sebenarnya disiapkan Tsubaraya untuk kembali ke kisah era Showa, sudah diiklankan. Ternyata, belajar dari Nexus yang semula diprduksi 50 episode tetapi terpaksa dipotong dan tamat di episode 38, Tsuburaya bermaksud mengantisipasi serial ini gagal sehingga dari awal memang sengaja jumlah episodenya sudah demikian adanya, yaitu hanya 40 episode.Dalam dunia Max berada, dikisahkan bahwa sejak zaman dulu, bumi memiliki banyak peradaban lain selain peradaban manusia yang mendiami permukaan bumi. Karena itu, sering timbul konflik di antara mereka. Namun, entah beratus-ratus tahun kemudian, manusia abad sekarang tidak mengetahui hal itu dan hidup dalam damai. Kebencian bangsa lain akan sikap manusia merupakan ancaman tersendiri yang tidak disadari oleh mereka. Sementara itu, manusia lebih difokuskan pada monster-monster dari luar angkasa yang secara nyata menyerang Bumi. Di sinilah Max muncul.\n" +
                    "\n" +
                    "Touma Kaito bermimpi untuk masuk DASH karena sebelumnya ia adalah relawan yang sering menyelamatkan orang-orang dari bencana alam. Namun, ia gagal dalam tes masuk karena dinilai terlalu berjiwa panas saat berusaha melindungi orang tanpa berpikir panjang dan sering tidak sadar melakukan tindakan berlebihan yang membahayakan keselamatannya sendiri. Kaito memiliki alasan tersendiri dan tetap bersikeras untuk masuk DASH. Suatu hari, ia yang masih menjadi anggota magang, nekat menggantikan salah seorang anggota DASH yang terluka untuk membantu menghalau monster demi menghindari banyaknya korban jiwa yang berjatuhan. Di saat kritis, Touma kemudian menerima kekuatan Ultraman dan memulai tanggung jawabnya yang besar. Ia menamakan Ultraman dalam dirinya Max. Karena kegigihannya ini, akhirnya Kaito pun diterima menjadi anggota DASH.",
            "2006",
            "\t\n" +
                    "Kazuo Tsuburaya",
            "https://upload.wikimedia.org/wikipedia/en/thumb/3/39/Maxposter.jpg/220px-Maxposter.jpg",
            "https://static.wikia.nocookie.net/ultra/images/5/5a/Kazuo_Tsuburaya.png/revision/latest?cb=20230314164202",
        ),
        Ultra(
            "15",
            "Ultraman Ginga",
            "Ultraman Ginga (ウルトラマンギンガ Urutoraman Ginga?) adalah Ultraman dari masa depan yang tidak diketahui yang pernah menjadi satu entitas Dark Lugiel dengan siapa yang terakhir dipisahkan dari sebelum Perang Spark Gelap. Setelah perang, dia terjebak dalam bentuk Spark Doll. Boneka dan Ginga Spark membuat jalan mereka ke Bumi dan ke tangan Hikaru Raido, yang menggunakan kedua item ini untuk berubah menjadi Ultraman Ginga dan pengguna pertarungan Dark Spark Doll. Ketika dia kembali ke ruang angkasa, dia meninggalkan percikannya di milik Hikaru supaya dia bisa datang untuk membantu Bumi, bahkan jika dia berada jauh di galaksi.\n" +
                    "\n" +
                    "Dua tahun kemudian, dia kembali ke Bumi untuk melawan ancaman Alien Chibu Exceller, yang merencanakan untuk menggunakan Victorium yang dicuri untuk menghidupkan kembali setengah lainnya Lugiel dan bergabung dengan Bumi yang terlahir sebagai Pahlawan Ultra Ultraman Victory. Pertemuan mereka dengan Etelgar dan Ultraman Zero akhirnya mengarah pada fusi Ultraman Ginga Victory.Kedua Ultraman Ginga dan Dark Lugiel berasal dari ruang angkasa yang didirikan di suatu tempat di masa depan. Keduanya awalnya satu kesatuan. Namun, kedua Ginga dan Lugiel memiliki pola pikir yang berbeda dari perdamaian. Lugiel menyatakan bahwa untuk menciptakan \"surga tertinggi\", semua bentuk kehidupan harus dihentikan sementara namun Ginga keberatan, mengatakan bahwa semua bentuk kehidupan membawa kemakmuran. Keduanya akhirnya berpisah dengan Ginga membawa cahaya dan Lugiel membawa kegelapan.Dark Lugiel mengatur Dark Spark War yang mengamuk di antara sisi yang baik dan sisi kejahatan, seperti yang ditunjukkan oleh para peserta, monster dan alien jahat dari seberang alam semesta. Diketahui bahwa Ginga, dengan Ginga Spark, sebelumnya melawan pemilik Dark Spark, tapi seperti mungkin setiap Ultra dan monster dalam perang telah disegel oleh Dark Spark menjadi bentuk sebuah tokoh aksi disebut Spark Doll. Sekarang diketahui bahwa ini disebabkan oleh bentrokan antara Ginga Spark dan Dark Spark, yang menyegel kedua kombatan tersebut. Setelah itu peristiwa yang kemudian dikenal sebagai Perang Spark Gelap, karena endingnya, boneka-boneka ini kemudian jatuh ke Bumi di sebuah shower meteor dengan Spark Ginga dan Boneka Ginga tersembunyi di dalamnya. Ginga Spark kemudian disimpan di dalam Kuil Ginga oleh Hotsuma Raido.\n" +
                    "\n" +
                    "Beberapa saat kemudian, seorang pemuda bernama Hikaru Raido menemukan Ginga Spark, yang membuatnya bergabung dengan tokoh aksi dan memiliki kemampuan makhluk dalam sosok aksi melalui proses yang disebut UltraLive. Tidak seperti Spark Doll lainnya, Mark of Courage Hikaru harus bersinar agar Spark Doll Ginga dipanggil dari dalam. Ginga pertama kali dipanggil oleh Hikaru untuk bertarung dengan Thunder Darambia, dan selesaikan rakasa itu dengan menggunakan Ginga Thunderbolt. Setelah itu Hikaru mengklaim Boneka Thunder Darambia. Ini membantunya dalam banyak pertempuran melawan manusia dan bahkan beberapa temannya sendiri yang Dark Live menjadi kaiju dan alien (Thunder Darambia, Kemur Man, King Pandon, Ragon, dll) melalui Spark Doll dan Dark Dummy Spark yang didistribusikan oleh agen the mastermind; Alien Valky, Alien Icarus dan Alien Nackle Gray. Pada saat yang sama, ini memungkinkan Hikaru untuk menerima Spark Doll dari monster yang dia kalahkan.",
            "2013",
            "Keiichi Hasegawa",
            "https://tsuburaya-prod.com/wp-content/uploads/2021/11/P2013_%E3%82%AE%E3%83%B3%E3%82%AC_01B.jpg",
            "https://static.wikia.nocookie.net/ultra/images/a/a6/Keiichi_Hasegawa.png/revision/latest?cb=20221216100856"
        ),
        Ultra(
            "16",
            "Ultraman X",
            "Ultraman X (ウルトラマンXエックス Urutoraman Ekkusu?) adalah pahlawan utama dalam serinya. Awalnya, dia adalah seorang Pahlawan Ultra yang mengejar lawannya Greeza ke tata surya dan membuangnya ke arah matahari, tapi hal itu telah memicu Ultra Flare dan mengorbankan tubuh fisiknya, terjebak secara permanen dalam keadaan digital yang dia gunakan untuk perjalanan antar bintang. Pada hari ini, dia terikat dengan anggota Xio, Daichi Ozora dan menghuni X Devizer anak muda untuk meminjamkan kekuatannya dalam melawan ancaman monster dengan bentuk fisiknya. Ketika Greeza tampak hidup dan melancarkan serangan ke Bumi, X terikat dengan berbagai macam Spark Doll dan akhirnya mengalahkan lawan lamanya.\n" +
                    "\n" +
                    "Keinginannya untuk mendapatkan kembali tubuh fisiknya mulai terwujud setelah pertempuran melawan Zaigorg tapi awalnya meninggalkan Daichi untuk melindungi galaksi, dia kembali lagi ke pemuda itu dalam menghadapi Desastro.Nama X mungkin merupakan singkatan dari awalan \"Exo-\" yang berarti di luar dalam bahasa Yunani. Menurut Daichi, namanya menunjukkan Ultra sebagai prajurit tak dikenal di Bumi, karena dia terdaftar di luar kategorisasi dan dengan demikian namanya \"Ultraman X\". Namanya juga bisa menjadi singkatan dari kata Yunani \"Xenos\" yang berarti orang asing, karena tak seorang pun di Bumi pernah mengalami makhluk seperti dia.Beberapa waktu yang lalu, Ultraman X bertempur melawan seorang sosok keunguan yang tidak dikenal dalam mode Flash Travel-nya. X muncul sebagai pemenang, saat dia mengetuk lawannya ke matahari tapi ini menjadi kehancurannya, yang dimulai sebuah suar surya yang memandikan Bumi dengan cahaya ungu dan membangunkan Spark Doll dari bawah Bumi. Sebagai hasil dari pertempuran, tubuh X didigitalkan dan dikirim ke Bumi. Selama waktunya di luar angkasa, dia menerima frekuensi aneh yang berasal dari Daichi, hosti manusia masa depannya.\n" +
                    "\n" +
                    "Lima belas tahun kemudian, saat raksasa Demaaga mengamuk di sebuah kota, dia diselamatkan dan diikat dengan petugas Xio, Daichi Ozora, di mana tubuhnya akhirnya terwujud kembali. X dan Daichi dimana bisa menghadapi dan menghancurkan Demaaga. Setelah pertempuran, X mencari bantuan Daichi dalam memulihkan tubuh fisik lamanya karena yang terakhir setuju untuk melakukannya. Mulai dari pertarungannya dengan Birdon, X memperoleh kemampuan MonsArmor dari Alien Fanton Guruman, memungkinkan dia untuk menggunakan kekuatan Cyber Kaiju. Namun terlepas dari MonsArmor, saat dalam perang melawan teroris Bemstar Zarab, X dimakan hidup bersama dengan Daichi, dan akhirnya diselamatkan oleh Wataru Kazama dan Hayato Kijima dan anggota Xio lainnya sebelum bisa dicerna oleh Bemstar.",
            "2015",
            "Yuji Kobayashi",
            "https://static.wikia.nocookie.net/ultra/images/6/6e/IMG_1207.jpg/revision/latest/scale-to-width-down/500?cb=20170904235800",
            "https://static.wikia.nocookie.net/ultra/images/8/85/Yuji_Kobayashi.png/revision/latest?cb=20230219180137"
        ),
        Ultra(
            "17",
            "Ultraman Z",
            "Ultraman ZZett (ウルトラマンゼット, Urutoraman Zetto) adalah Ultra Hero tituler dari seri Ultraman Z. Dia adalah murid Ultraman Zero yang memproklamirkan diri. Untuk melindungi Bumi dari monster yang mengamuk, Z terikat dengan anggota STORAGE Haruki Natsukawa selama pertarungan melawan Genegarg.Z adalah huruf terakhir dalam alfabet Inggris, dan memunculkan rasa finalitas. Di alam semesta, ayah baptis Z, Ultraman Ace, memberinya nama ini dengan harapan Z akan menjadi \"Pahlawan Terakhir\" yang mungkin membawa perdamaian ke alam semesta suatu hari nanti.\n" +
                    "\n" +
                    "Semua nama bentuk Ultra Fusion Z dimulai dengan huruf Yunani, termasuk urutan kemunculannya secara seri.Bersama Ultraman Taiga, Z dan sebagian besar Ultra muda di Negeri Cahaya menerima pendidikan formal dari Ultraman 80. Saudara Z mengagumi Ultraman Zero dan mencari magang di bawah bimbingan idolanya dengan benar-benar bertemu dengannya selama pertemuan pertama mereka. Zero awalnya enggan mengambil siswa lain di bawah sayapnya, namun melanjutkan untuk melakukannya setelah beberapa persuasi dari Z. Z dan Pertemuan Zero Selain memberikan pelatihan fisik, Z diberi pengarahan tentang eksploitasi Zero di masa lalu, bertemu setidaknya dua anggota Ultimate Force Zero dan menerima ilmu yang berharga. Teman Master Monster Kapsul Handal Ultraman dan Sejarah Kuno Ultramen di Ruang-Waktu Lain Adik Baja Tentang Ayah Master Zero Untuk memerangi kasus Serpihan Iblis di luar angkasa, Z diperintahkan oleh Zero untuk menjadi subjek uji netral Ultraman Hikari untuk penciptaan sebuah perangkat baru. Hasilnya adalah Z Riser, dinamai berdasarkan nama pengujinya sendiri dengan kemampuan untuk menambah penggunanya dengan kekuatan Ultra Medals. Ultra Z Riser\n" +
                    "\n" +
                    "Untuk mengikuti jejak Zero lebih jauh lagi, Z memutuskan untuk mengikuti tes masuk Pasukan Pertahanan Antar Galaksi. Galaxy Rescue Force Setelah gagal dalam tes tertulis karena peran Zero dalam informasi yang salah, dia diberitahu tentang tes alternatif oleh Ultraman Mebius. Ujian Perekrutan ① Penantang/pengujinya ternyata adalah Zero, dan keduanya berduel satu sama lain untuk membuktikan nilai Z sebagai anggota Pasukan Pertahanan Antar Galaksi dan sebagai murid Zero. Ujian Perekrutan ② Zoffy memberi Z keanggotaan dalam organisasi karena lulus ujian, namun jalan masih panjang untuk mendapatkan persetujuan masternya.",
            "2020",
            "Kōta Fukihara",
            "https://static.wikia.nocookie.net/ultra/images/2/23/ZPoster1.jpg/revision/latest/scale-to-width-down/250?cb=20200325213055",
            "https://static.wikia.nocookie.net/ultramananthology/images/8/82/K%C5%8Dta_Fukihara.jpg/revision/latest?cb=20200526094550"
        ),
        Ultra(
            "18",
            "Ultraman Geed",
            "Ultraman Geed (ウルトラマンジード Urutoraman Jīdo?) adalah pahlawan utama dalam serinya. Anak sintetis dari Ultra Reionik Ultraman Belial yang terkenal, Geed lahir pada titik yang tidak diketahui dalam Crisis Impact, dan telah menghabiskan sebagian besar hidupnya di Bumi tanpa mengetahui asal-usulnya.Sebagai seorang Reibatos yang sangat terluka, yang berhasil bertahan dalam pertempuran terakhirnya dengan Ultraman Orb, mencoba untuk menghidupkan kembali Ultraman Belial, (hanya untuk gagal dan menyadari bahwa Belial masih hidup) Geed dalam bentuk Primitive-nya tiba dan menghabiskan Reibatos dengan Wrecking Burst-nya. Namun di episode terakhir serinya, terungkap bahwa Belial sebenarnya adalah orang yang membunuh Reibatos dengan Deathcium Ray-nya daripada Geed.Selama masa lalu, Geed diciptakan sebagai Ultra sintetis oleh Ultraman Belial dan 伏井出軽 (Fushiide Kei), pada dasarnya menciptakan Ultra buatan dengan menumbuhkan 朝倉陸 (Asakura Riku) dari materi genetik Belial.\n" +
                    "\n" +
                    "19 tahun kemudian, setelah serangkaian acara yang menyebabkan adopsi mantel anak laki-lakinya sebagai Ultraman (yang dia sebut sebagai \"Ultraman Geed\"), Ultraman Belial dan Fushiide Kei merencanakan rencana jangka panjang mereka dengan mengajaknya berkelahi melawan monster. serangan saat memanen Ultra Capsul dari hosti Little Star. Tentu saja, Asakura Riku juga segera belajar dari warisan sebenarnya sebagai anak Ultraman Belial dari operator Nebula House, RE.M.. Terlepas dari opini publik mengenai Geed (entah kesamaannya dengan Belial atau fakta bahwa kesetiaannya masih ambigu), Asakura Riku memutuskan untuk menggunakan kekuatan barunya untuk melindungi kemanusiaan. Seiring waktu Asakura Riku mendapatkan bentuk yang lebih baru dari Kapsul yang dia dapatkan dan bergabung dengan musuh ayahnya; Ultraman Zero.Selama pertarungan pertama dengan Pedanium Zetton, Riku mempelajari tujuan sebenarnya di balik kelahirannya dan pencurian semua kecuali satu kapsul membuat dia tidak berdaya sampai bertemu dengan Sui Asakura, seorang pria yang memberikan Riku namanya. Hal ini menyebabkan perolehan Kapsul Ayah Ultra, menggunakannya dengan Kapsul Zero untuk berubah menjadi Geed Magnificent dan memperbaharui semangatnya dengan melawan nasib yang telah dikenakan kepadanya sebelum mengembalikan Kapsulnya yang dicuri.",
            "2017",
            "Hirotaka Adachi",
            "https://upload.wikimedia.org/wikipedia/en/e/e9/Ultraman_Geed_The_Movie_Poster.jpg",
            "https://static.wikia.nocookie.net/ultra/images/a/ad/Otsuichi.png/revision/latest?cb=20230205063941",
        ),
        Ultra(
            "19",
            "Ultraman Trigger",
            "Ultraman Trigger (ウルトラマントリガー, Urutoraman Torigā) adalah Ultra Hero tituler dari serial Ultraman Trigger: New Generation Tiga. Dia adalah Ultraman kuno yang pernah berperang melawan kegelapan 30 juta tahun yang lalu dan dihidupkan kembali di era modern setelah tidur panjangnya.30 juta tahun sebelumnya, Trigger awalnya adalah Trigger Dark, anggota terkuat dan keempat dari Giants of Darkness, serta rekan tanding Darrgon dan kekasih Carmeara. Masa lalunya sebagai raksasa gelap awalnya tidak diketahui dan tercatat di bagian tersembunyi sebuah tablet batu kuno yang menggambarkan pertempuran Trigger melawan Raksasa Kegelapan. Pemicu Hati yang Goyah dan Raksasa Kegelapan lainnya menangkap Yuzare dan membawanya ke altar untuk membuka gerbang menuju Inti Keabadian. Di bawah instruksi Carmeara, Trigger Dark adalah Raksasa Kegelapan pertama yang mendekati objek tersebut. Sebelum dia bisa melakukan apa pun terhadapnya, Kengo Manaka, yang telah melakukan perjalanan kembali ke masa lalu melalui pusaran, memasuki Ruang Dalam Trigger dan meyakinkannya untuk beralih ke cahaya dan berjuang demi senyuman semua orang. Mereka akhirnya menyadari bahwa mereka adalah makhluk yang satu dan sama. Trigger Dark menjadi Ultraman Trigger, dan membuang mantan rekannya ke luar angkasa dengan bantuan Yuzare dan Eternity Core. Trigger kemudian tertidur di reruntuhan piramida terbalik di planet Mars, dan terlupakan oleh waktu. Patung batunya terletak di lantai bawah, sedangkan Circle Arms berada di lantai paling atas.These events were witnessed by Zabil and recorded on a tablet that he carved out of the stone from the pillars that the light of Trigger's Type Changes merged with, warning future generations of the three Giants of Darkness' eventual return. The tablet was unearthed at some point in time and placed in Akito Hijiri's lab the Nursedessei, where he studied its contents and managed to extract Trigger's light to create his Type Changes' Hyper Keys.",
            "2021",
            "Naoki Hayashi",
            "https://m.media-amazon.com/images/M/MV5BMzIzOGVlMDItNWMxOC00MWE4LTk2NGItNmRlZGEzYWYxOWRmXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_.jpg",
            "https://daed.nl/wp-content/uploads/2016/07/Naoki-Hayashi-1-1024x1024.jpg"
        ),
        Ultra(
            "20",
            "Ultraman Decker",
            "Ultraman Decker (ウルトラマンデッカー, Urutoraman Dekkā) adalah Ultra Hero tituler dari seri Ultraman Decker. Dia datang ke Bumi sebagai cahaya misterius selama serangan Spheres, dan terikat dengan Kanata Asumi dari GUTS-Select yang baru direformasi.Setelah beberapa abad, umat manusia mulai berekspansi ke luar angkasa, menghadapi banyak ras alien lainnya dalam prosesnya. Kemajuan mereka terhenti oleh kemunculan Sphere, yang dilawan manusia dengan bantuan sekutu mereka, termasuk inkarnasi Yuzare pada saat itu, dan Ultraman lainnya. Pada titik tertentu, Decker Asumi memperoleh kekuatan cahaya, dan mampu berubah menjadi Ultraman Decker menggunakan Ultra D Flasher, namun mereka masih tidak dapat sepenuhnya mengusir Sphere.\n" +
                    "\n" +
                    "Sphere akhirnya mencapai Planet Bazdo dan memenjarakannya di Sphere Barrier. Sementara penduduknya masih melawan, mantan sekutu Decker, Agams, menjadi benci terhadap umat manusia, menyalahkan mereka dan perluasan ruang angkasa mereka yang membawa Sphere ke planet mereka. Hal ini menyebabkan dia menciptakan sistem distorsi ruang-waktu untuk kembali ke masa lalu, membawa Sphere bersamanya untuk menyerang Bumi masa lalu untuk mencegah kehancuran dunia asalnya di masa depan. Decker berusaha mengikutinya kembali ke masa lalu tetapi Agams menghancurkan sistem tersebut sebelum orang lain dapat menggunakannya. Putus asa untuk menghentikan rencana Agams, Decker mengirim Ultra D Flasher kembali ke masa lalu, berharap cahaya juga akan ada di sana.Ultraman Decker muncul ketika Kanata Asumi dikonsumsi oleh Sphere Soldier. Cahayanya diberikan kepada Kanata, memberinya Ultra D Flasher dan Kartu Ultra Dimensi, secara telepati memerintahkan dia untuk berubah, keluar dari Sphere. Decker dan Kanata bertarung melawan Spheresaurus dan mengalahkan monster itu sebelum terbang ke luar angkasa untuk melawan Sphere lainnya, tetapi terjatuh kembali ke Bumi, kehabisan energi sementara gagal mencegah Sphere membungkus Bumi dalam Sphere Barrier mereka. Kanata relatif tidak terluka saat mendarat, namun Ultra D Flasher menghilang setelahnya.",
            "2022",
            "\t\n" +
                    "Toshizo Nemoto",
            "https://m.media-amazon.com/images/M/MV5BOTA4MjZjOTMtYzVlMC00NTViLWE0YzEtNDdmOTU5ZDU2ZDBmXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_FMjpg_UX1000_.jpg",
            "https://static.wikia.nocookie.net/ultra/images/6/63/ToshizoNemotoIMG.png/revision/latest?cb=20221231200732"
        )
    )
}